# **Scramble: Matrix**

Let $$ A = \begin{bmatrix} 1 & 3 & 2 & -1 \\ 3 & 3 & 4 & 1 \\ 1 & 0 & 0 & 0 \end{bmatrix} $$ 

TODO:
- Import `numpy` in as `np`, 
- read the matrix $A$ in as a numpy array. Assign it the character `A`, 
- assign $x$ to be the third column.
- print $x$.
  

---
Import `numpy` in as `np`, 

In [1]:
import numpy as np

read the matrix $A$ in as a numpy array, 

In [7]:
A =np.array([[1, 3, 2, -1], [3, 3, 4, 1], [1, 0, 0, 0]])
print(A)

[[ 1  3  2 -1]
 [ 3  3  4  1]
 [ 1  0  0  0]]


assign $x$ to be the third column.

In [10]:
x = A[:,2]

print $x$.

---

In [9]:
print(x)

[2 4 0]
